version: '3'
services:

 simpleproject:
    image: tcsantos/simpleproject:latest
    ports:
       - "8080:8080"
    networks:
        - simple-project-network

 postgres:
    image: postgres
    ports:
       - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
        - simple-project-network

networks: 
     simple-project-network:

