e8piVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: simpleproject
  labels:
    app: simpleproject
spec:
  selector:
    matchLabels:
      app: simpleproject
  replicas: 2
  template:
    metadata:
      labels:
        app: simpleproject
    spec:
      containers:
        image: tcsantos/simpleproject:latest
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 1500m
            memory: 1536Mi
        ports:
        - containerPort: 8080
